In [2]:
# Numpy is the module of python which is used for scientifics computing
# Creating a single D array

import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
b = np.arange(10,200,90)
b

array([ 10, 100, 190])

In [11]:
#  how to create the zeros element in the array 

c = np.zeros(8)  # here we specify that how to create the zeros element by giving the rows and columns
c

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
print(c.reshape((2,2,2))) # this will change to shape of the origial array
print(c.ravel())  # This back to orginal shape techanical term to convert to linear array

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[0. 0. 0. 0. 0. 0. 0. 0.]


 how to do the operation with the txt file means
 how to read the data from the txt fieles

In [21]:
arr = np.loadtxt('d.txt')
arr

ValueError: could not convert string to float: 'Audience'